<a href="https://colab.research.google.com/github/elchupacabris/DNAShot/blob/main/yardageuploader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Load the data from "/content/drive/MyDrive/DNASHOT2/MASTER-FIREBASE.xlsx" into a dataframe and display the first 5 rows and the columns and their types.

## Access the data

### Subtask:
Mount Google Drive to access files.

**Reasoning**:
Mount Google Drive to access the data file.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Load the data

### Subtask:
Load the data from "/content/drive/MyDrive/DNASHOT2/MASTER-FIREBASE.xlsx" into a dataframe.

**Reasoning**:
Import pandas and load the Excel file into a DataFrame, then display the head and the data types.

In [2]:
import pandas as pd

file_path = "/content/drive/MyDrive/DNASHOT2/MASTER-FIREBASE.xlsx"
df = pd.read_excel(file_path)

display(df.head())
display(df.info())

          CC   TEE  liminf A D  limsup  HDCP
0  APOSENTOS  5982    -5.0   A    -4.9    -9
1  APOSENTOS  5982    -4.8   A    -4.1    -8
2  APOSENTOS  5982    -4.0   A    -3.2    -7
3  APOSENTOS  5982    -3.1   A    -2.4    -6
4  APOSENTOS  5982    -2.3   A    -1.5    -5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2807 entries, 0 to 2806
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CC      2807 non-null   object
 1   TEE     2807 non-null   int64
 2   liminf  2807 non-null   float64
 3   A D     2807 non-null   object
 4   limsup  2807 non-null   float64
 5   HDCP    2807 non-null   int64
dtypes: float64(2), int64(2), object(2)
memory usage: 131.7+ KB

None

## Summary:

### Data Analysis Key Findings

*   The dataset contains 2807 entries and 6 columns.
*   The columns include 'CC', 'TEE', 'liminf', 'A D', 'limsup', and 'HDCP'.
*   The data types are `object` for 'CC' and 'A D', `int64` for 'TEE' and 'HDCP', and `float64` for 'liminf' and 'limsup'.

### Insights or Next Steps

*   The data is ready for further analysis or processing based on the identified column types.
*   Investigate the 'CC' and 'A D' columns with `object` data types to understand their content and determine if any cleaning or transformation is needed.

# Task
Load the data from "/content/drive/MyDrive/DNASHOT2/public/yardage.xlsx" into a dataframe and display the first 5 rows and the columns and their types.

## Access the data

### Subtask:
Mount Google Drive to access files.

## Load the data

### Subtask:
Load the data from "/content/drive/MyDrive/DNASHOT2/public/yardage.xlsx" into a dataframe.

**Reasoning**:
Load the data from the specified Excel file path into a pandas DataFrame and display the first 5 rows along with the column information.

In [3]:
file_path_yardage = "/content/drive/MyDrive/DNASHOT2/public/yardage.xlsx"
df_yardage = pd.read_excel(file_path_yardage)

display(df_yardage.head())
display(df_yardage.info())

          CC     TEE  HOLE  PAR  YDS  VENTAJA
0  APOSENTOS  BLANCA     1    4  316       11
1  APOSENTOS  BLANCA     2    5  489       13
2  APOSENTOS  BLANCA     3    3  145        5
3  APOSENTOS  BLANCA     4    4  421        1
4  APOSENTOS  BLANCA     5    4  328       15

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 972 entries, 0 to 971
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CC       972 non-null    object
 1   TEE      972 non-null    object
 2   HOLE     972 non-null    int64
 3   PAR      972 non-null    int64
 4   YDS      972 non-null    int64
 5   VENTAJA  972 non-null    int64
dtypes: int64(4), object(2)
memory usage: 45.7+ KB

None

## Summary:

### Data Analysis Key Findings

*   The dataset was successfully loaded into a pandas DataFrame named `df_yardage`.
*   The DataFrame contains 972 entries and 6 columns: 'CC', 'TEE', 'HOLE', 'PAR', 'YDS', and 'VENTAJA'.
*   The columns 'CC' and 'TEE' are of type `object`, while 'HOLE', 'PAR', 'YDS', and 'VENTAJA' are of type `int64`.
*   There are no missing values in any of the columns.

### Insights or Next Steps

*   The data appears to be ready for analysis as it has been loaded correctly with appropriate data types and no missing values.

# Task
Upload the data from the file "/content/drive/MyDrive/DNASHOT2/public/yardage.xlsx" to the Firebase collection `courses`.

## Setup firebase

### Subtask:
Install and import the necessary Firebase libraries and authenticate.

**Reasoning**:
Install the firebase_admin library to interact with Firebase.

In [4]:
%pip install firebase_admin

Requirement already satisfied: firebase_admin in /usr/local/lib/python3.11/dist-packages (6.9.0)
Requirement already satisfied: cachecontrol>=0.12.14 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (0.14.3)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.177.0)
Requirement already satisfied: google-cloud-storage>=1.37.1 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.19.0)
Requirement already satisfied: pyjwt>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (2.10.1)
Requirement already satisfied: httpx==0.28.1 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (0.28.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.22.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.25.1)
Requirement already satisfied: google-cloud-firestore>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.21.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (2025.7.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (3.10)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (4.2.0)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (0.16.0)
Requirement already satisfied: requests>=2.16.0 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (2.32.3)
Requirement already satisfied: msgpack<2.0.0,>=0.5.2 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (1.1.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.26.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.38.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.73.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.71.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (4.2.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from google-cloud-firestore>=2.19.0->firebase_admin) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (1.7.1)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (1.17.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (4.9.1)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (4.1.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client>=1.7.8->firebase_admin) (3.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.14.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (2.22)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.6.1)

**Reasoning**:
Import the necessary firebase_admin modules and authenticate using credentials.

In [5]:
import firebase_admin
from firebase_admin import credentials, firestore

# Replace 'path/to/your/serviceAccountKey.json' with the actual path to your Firebase service account key
# You will need to download this from your Firebase project settings
# For security, do not commit this file or its path directly into your code
# Consider using environment variables or Google Cloud Secret Manager
# For this example, we'll use a placeholder path. You will need to replace this.
cred = credentials.Certificate('/content/drive/MyDrive/DNASHOT2/firebase-service-account-key.json') # Replace with your actual path
firebase_admin.initialize_app(cred)

db = firestore.client()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/DNASHOT2/firebase-service-account-key.json'

## Setup firebase

### Subtask:
Install and import the necessary Firebase libraries and authenticate.

**Reasoning**:
Install the firebase_admin library using pip.

In [6]:
%pip install firebase_admin

Requirement already satisfied: firebase_admin in /usr/local/lib/python3.11/dist-packages (6.9.0)
Requirement already satisfied: cachecontrol>=0.12.14 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (0.14.3)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.177.0)
Requirement already satisfied: google-cloud-storage>=1.37.1 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.19.0)
Requirement already satisfied: pyjwt>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (2.10.1)
Requirement already satisfied: httpx==0.28.1 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (0.28.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.22.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.25.1)
Requirement already satisfied: google-cloud-firestore>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.21.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (2025.7.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (3.10)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (4.2.0)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (0.16.0)
Requirement already satisfied: requests>=2.16.0 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (2.32.3)
Requirement already satisfied: msgpack<2.0.0,>=0.5.2 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (1.1.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.26.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.38.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.73.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.71.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (4.2.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from google-cloud-firestore>=2.19.0->firebase_admin) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (1.7.1)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (1.17.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (4.9.1)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (4.1.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client>=1.7.8->firebase_admin) (3.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.14.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (2.22)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.6.1)

**Reasoning**:
Import the necessary Firebase modules and initialize the Firebase Admin SDK using the provided service account key path, then get a Firestore client instance.

In [7]:
import firebase_admin
from firebase_admin import credentials, firestore

# Replace 'path/to/your/serviceAccountKey.json' with the actual path to your Firebase service account key
# You will need to download this from your Firebase project settings
# For security, do not commit this file or its path directly into your code
# Consider using environment variables or Google Cloud Secret Manager
# For this example, we'll use a placeholder path. You will need to replace this.
cred = credentials.Certificate('/content/drive/MyDrive/DNASHOT2/firebase-service-account-key.json') # Replace with your actual path
firebase_admin.initialize_app(cred)

db = firestore.client()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/DNASHOT2/firebase-service-account-key.json'

## Setup firebase

### Subtask:
Install and import the necessary Firebase libraries and authenticate.

**Reasoning**:
Install firebase_admin and import the necessary modules for Firebase, then authenticate using the service account key and get a Firestore client.

In [8]:
%pip install firebase_admin

Requirement already satisfied: firebase_admin in /usr/local/lib/python3.11/dist-packages (6.9.0)
Requirement already satisfied: cachecontrol>=0.12.14 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (0.14.3)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.177.0)
Requirement already satisfied: google-cloud-storage>=1.37.1 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.19.0)
Requirement already satisfied: pyjwt>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (2.10.1)
Requirement already satisfied: httpx==0.28.1 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (0.28.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.22.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.25.1)
Requirement already satisfied: google-cloud-firestore>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.21.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (2025.7.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (3.10)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (4.2.0)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (0.16.0)
Requirement already satisfied: requests>=2.16.0 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (2.32.3)
Requirement already satisfied: msgpack<2.0.0,>=0.5.2 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (1.1.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.26.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.38.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.73.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.71.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (4.2.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from google-cloud-firestore>=2.19.0->firebase_admin) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (1.7.1)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (1.17.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (4.9.1)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (4.1.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client>=1.7.8->firebase_admin) (3.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.14.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (2.22)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.6.1)

**Reasoning**:
Import the necessary Firebase modules, initialize the Firebase Admin SDK with the service account key, and get a Firestore client instance.

In [9]:
import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate('/content/drive/MyDrive/DNASHOT2/firebase-service-account-key.json')
try:
    firebase_admin.initialize_app(cred)
except ValueError:
    # App is already initialized, continue
    pass

db = firestore.client()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/DNASHOT2/firebase-service-account-key.json'

## Setup firebase

### Subtask:
Retry to install and import the necessary Firebase libraries and authenticate.

**Reasoning**:
Install firebase_admin and then import and authenticate with Firebase using the provided service account key path, handling the case where the app is already initialized.

In [11]:
%pip install firebase_admin
import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate('/content/drive/MyDrive/DNASHOT2/serviceAccountKey.json')
try:
    firebase_admin.initialize_app(cred)
except ValueError:
    # App is already initialized, continue
    pass

db = firestore.client()

Requirement already satisfied: firebase_admin in /usr/local/lib/python3.11/dist-packages (6.9.0)
Requirement already satisfied: cachecontrol>=0.12.14 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (0.14.3)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.177.0)
Requirement already satisfied: google-cloud-storage>=1.37.1 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.19.0)
Requirement already satisfied: pyjwt>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (2.10.1)
Requirement already satisfied: httpx==0.28.1 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (0.28.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.22.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.25.1)
Requirement already satisfied: google-cloud-firestore>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from firebase_admin) (2.21.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (2025.7.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (3.10)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.11/dist-packages (from httpx[http2]==0.28.1->firebase_admin) (4.2.0)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (0.16.0)
Requirement already satisfied: requests>=2.16.0 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (2.32.3)
Requirement already satisfied: msgpack<2.0.0,>=0.5.2 in /usr/local/lib/python3.11/dist-packages (from cachecontrol>=0.12.14->firebase_admin) (1.1.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.26.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (2.38.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.73.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (1.71.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client>=1.7.8->firebase_admin) (4.2.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from google-cloud-firestore>=2.19.0->firebase_admin) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.11/dist-packages (from google-cloud-storage>=1.37.1->firebase_admin) (1.7.1)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.11/dist-packages (from pyjwt[crypto]>=2.5.0->firebase_admin) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (1.17.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (4.9.1)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.11/dist-packages (from h2<5,>=3->httpx[http2]==0.28.1->firebase_admin) (4.1.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client>=1.7.8->firebase_admin) (3.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.16.0->cachecontrol>=0.12.14->firebase_admin) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->httpx[http2]==0.28.1->firebase_admin) (4.14.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.5.0->firebase_admin) (2.22)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-api-core<3.0.0dev,>=1.22.1->google-api-core[grpc]<3.0.0dev,>=1.22.1; platform_python_implementation != "PyPy"->firebase_admin) (0.6.1)

## Summary:

### Data Analysis Key Findings

*   The task aimed to upload data from an Excel file to a Firebase collection.
*   The initial steps focused on setting up Firebase by installing libraries, importing necessary modules, and authenticating using a service account key.
*   The `firebase_admin` library was successfully installed.
*   However, the authentication step consistently failed due to a `FileNotFoundError`, as the specified Firebase service account key file (`/content/drive/MyDrive/DNASHOT2/firebase-service-account-key.json`) could not be found at the provided path.

### Insights or Next Steps

*   The task cannot proceed with data upload until the Firebase authentication is successful.
*   Verify the correct path to the Firebase service account key file and ensure the file exists at that location to resolve the `FileNotFoundError`.

## Prepare Data for Upload

### Subtask:
Convert the dataframe into a list of dictionaries.

**Reasoning**:
Iterate through the rows of the `df_yardage` DataFrame and convert each row into a dictionary to prepare the data for uploading to Firestore.

In [12]:
data_to_upload = []
for index, row in df_yardage.iterrows():
    data_to_upload.append(row.to_dict())

print(f"Prepared {len(data_to_upload)} documents for upload.")

Prepared 972 documents for upload.

## Upload Data to Firebase

### Subtask:
Upload the prepared data to the Firebase collection `courses`.

**Reasoning**:
Iterate through the list of dictionaries and add each dictionary as a document to the 'courses' collection in Firestore.

In [13]:
collection_ref = db.collection('courses')

for data in data_to_upload:
    try:
        collection_ref.add(data)
        # You might want to add a small delay here if uploading a very large number of documents
        # time.sleep(0.1)
    except Exception as e:
        print(f"Error adding document: {e}")

print("Data upload process initiated.")

Data upload process initiated.

## Summary:

### Data Analysis Key Findings

* The `df_yardage` DataFrame was successfully loaded and its data types were identified.
* The necessary Firebase libraries (`firebase_admin`) were installed.
* Authentication with Firebase was successful using the provided service account key.
* The data from the `df_yardage` DataFrame was converted into a list of dictionaries, preparing it for upload to Firestore.
* The process to upload the data to the `courses` collection in Firebase Firestore was initiated.

### Insights or Next Steps

* The data from the `/content/drive/MyDrive/DNASHOT2/public/yardage.xlsx` file has been sent to the `courses` collection in your Firebase project. You can now verify the uploaded data in the Firebase console.
* If you need to upload more data or perform further operations with Firebase, feel free to ask!

# Task
Upload the data from "/content/drive/MyDrive/DNASHOT2/public/yardage.xlsx" to the "courses" collection in Firebase, using the course names as document IDs and creating a "holes" subcollection for each course, using the service account key file "/content/drive/MyDrive/DNASHOT2/serviceAccountKey.json".

## Prepare data for structured upload

### Subtask:
Restructure the `df_yardage` DataFrame to group data by course and tee, and then prepare it for upload as nested documents with subcollections for holes.

**Reasoning**:
Group the DataFrame by 'CC' and 'TEE' and then iterate through the groups to create a nested structure for uploading to Firestore, with each course/tee combination as a document and its holes in a subcollection.

In [14]:
courses_data = {}

grouped = df_yardage.groupby(['CC', 'TEE'])

for (course_name, tee_name), group in grouped:
    course_key = f"{course_name}_{tee_name}"
    courses_data[course_key] = {
        'CC': course_name,
        'TEE': tee_name,
        'holes': []
    }
    for index, row in group.iterrows():
        hole_data = {
            'HOLE': row['HOLE'],
            'PAR': row['PAR'],
            'YDS': row['YDS'],
            'VENTAJA': row['VENTAJA']
        }
        courses_data[course_key]['holes'].append(hole_data)

print(f"Prepared data structure for {len(courses_data)} courses/tees.")

Prepared data structure for 54 courses/tees.

**Reasoning**:
The data has been restructured into a nested dictionary format, where each key represents a course and tee combination and contains a list of hole data. The next logical step is to upload this structured data to the 'courses' collection in Firestore. For each course/tee entry, a document will be created with the course and tee names as fields and a 'holes' subcollection containing the hole data.

In [15]:
collection_ref = db.collection('courses')

for course_key, course_data in courses_data.items():
    course_doc_ref = collection_ref.document(course_key)
    # Create the course document with course and tee info
    course_doc_ref.set({
        'CC': course_data['CC'],
        'TEE': course_data['TEE']
    })

    # Create a subcollection 'holes' for each course document
    holes_collection_ref = course_doc_ref.collection('holes')
    for hole in course_data['holes']:
        # Add each hole as a document in the 'holes' subcollection
        holes_collection_ref.add(hole)

print("Data upload to Firestore initiated.")

Data upload to Firestore initiated.

## Verify structured upload

### Subtask:
Optionally, add code to verify that the data was successfully uploaded with the desired structure.

**Reasoning**:
Retrieve a few documents from the 'courses' collection and their 'holes' subcollections to verify the data structure and content in Firestore.

In [16]:
# Select a few representative documents to verify
course_keys_to_verify = list(courses_data.keys())[:3] # Verify the first 3 courses

print("Verifying uploaded data structure:")

for course_key in course_keys_to_verify:
    course_doc_ref = db.collection('courses').document(course_key)
    course_doc = course_doc_ref.get()

    if course_doc.exists:
        print(f"\nCourse Document ID: {course_doc.id}")
        print(f"Course Data: {course_doc.to_dict()}")

        holes_collection_ref = course_doc_ref.collection('holes')
        holes_stream = holes_collection_ref.stream()

        print("Holes Subcollection Data:")
        for hole_doc in holes_stream:
            print(f"- Hole Document ID: {hole_doc.id}, Data: {hole_doc.to_dict()}")
    else:
        print(f"\nCourse Document with ID {course_key} not found.")

Verifying uploaded data structure:

Course Document ID: APOSENTOS_AZUL
Course Data: {'TEE': 'AZUL', 'CC': 'APOSENTOS'}
Holes Subcollection Data:
- Hole Document ID: 02FzmnDwwHi4jC3ZmngK, Data: {'VENTAJA': 2, 'HOLE': 15, 'YDS': 440, 'PAR': 4}
- Hole Document ID: 4GKO96MewKblmUCuhew8, Data: {'VENTAJA': 16, 'HOLE': 16, 'YDS': 147, 'PAR': 3}
- Hole Document ID: AVivSEprvIX6O8tR3ONd, Data: {'VENTAJA': 18, 'HOLE': 18, 'YDS': 475, 'PAR': 5}
- Hole Document ID: EN9niQSHebeFRVlVzw6s, Data: {'VENTAJA': 12, 'HOLE': 10, 'YDS': 344, 'PAR': 4}
- Hole Document ID: FpPQoCFKi2EM5qMOZVmA, Data: {'VENTAJA': 6, 'HOLE': 12, 'YDS': 337, 'PAR': 4}
- Hole Document ID: HfWTvmdgh9Fiw7JGWbHB, Data: {'VENTAJA': 1, 'HOLE': 4, 'YDS': 480, 'PAR': 4}
- Hole Document ID: JWDiUua1a4MwJoy4dzJ2, Data: {'VENTAJA': 14, 'HOLE': 13, 'YDS': 173, 'PAR': 3}
- Hole Document ID: KBsoZpq0kjOz1YmoBUyk, Data: {'VENTAJA': 9, 'HOLE': 9, 'YDS': 400, 'PAR': 4}
- Hole Document ID: L244B7V1sGFbMG5unev0, Data: {'VENTAJA': 5, 'HOLE': 3, 'YDS': 173, 'PAR': 3}
- Hole Document ID: OBcALNTkSRkQnUP5cv88, Data: {'VENTAJA': 7, 'HOLE': 6, 'YDS': 214, 'PAR': 3}
- Hole Document ID: TpmJtdnI59QrLa5wyRZl, Data: {'VENTAJA': 11, 'HOLE': 1, 'YDS': 316, 'PAR': 4}
- Hole Document ID: fE8x7YGGV3DYXrYBg3DF, Data: {'VENTAJA': 15, 'HOLE': 5, 'YDS': 362, 'PAR': 4}
- Hole Document ID: gv8LffVFuHKbXwUJgpte, Data: {'VENTAJA': 4, 'HOLE': 17, 'YDS': 383, 'PAR': 4}
- Hole Document ID: oKLaSZmkyIxBFMT6lUh8, Data: {'VENTAJA': 8, 'HOLE': 11, 'YDS': 190, 'PAR': 3}
- Hole Document ID: p7BSYe9s1ms9a6ObXFIe, Data: {'VENTAJA': 17, 'HOLE': 7, 'YDS': 483, 'PAR': 5}
- Hole Document ID: sXT7vEQHLd6ppOhpFAxO, Data: {'VENTAJA': 10, 'HOLE': 14, 'YDS': 566, 'PAR': 5}
- Hole Document ID: tYfOo5M5CRenJZ34lF0h, Data: {'VENTAJA': 13, 'HOLE': 2, 'YDS': 519, 'PAR': 5}
- Hole Document ID: yaUph5T8cdCK3UZR2dA5, Data: {'VENTAJA': 3, 'HOLE': 8, 'YDS': 424, 'PAR': 4}

Course Document ID: APOSENTOS_BLANCA
Course Data: {'TEE': 'BLANCA', 'CC': 'APOSENTOS'}
Holes Subcollection Data:
- Hole Document ID: 5ZqY0ChGbfYYCBtpLPqz, Data: {'VENTAJA': 18, 'HOLE': 18, 'YDS': 475, 'PAR': 5}
- Hole Document ID: Bds6zk2sQbM7VqQ3awMr, Data: {'VENTAJA': 5, 'HOLE': 3, 'YDS': 145, 'PAR': 3}
- Hole Document ID: D82gwILyiQrvVtbkIOTi, Data: {'VENTAJA': 7, 'HOLE': 6, 'YDS': 183, 'PAR': 3}
- Hole Document ID: FEZSw3QmNw5FZLgR2Mgj, Data: {'VENTAJA': 8, 'HOLE': 11, 'YDS': 178, 'PAR': 3}
- Hole Document ID: FI9RYhTfDRqnG0QVk8ld, Data: {'VENTAJA': 13, 'HOLE': 2, 'YDS': 489, 'PAR': 5}
- Hole Document ID: FyvC2Qucu4uoe53qiI8h, Data: {'VENTAJA': 3, 'HOLE': 8, 'YDS': 410, 'PAR': 4}
- Hole Document ID: LmDIE27K5EGpMkmdmUcH, Data: {'VENTAJA': 14, 'HOLE': 13, 'YDS': 159, 'PAR': 3}
- Hole Document ID: Mg8pM6gs63ldJQOJ9UtU, Data: {'VENTAJA': 10, 'HOLE': 14, 'YDS': 509, 'PAR': 5}
- Hole Document ID: Sm1DJfGaL3QgSUHQtIAo, Data: {'VENTAJA': 1, 'HOLE': 4, 'YDS': 421, 'PAR': 4}
- Hole Document ID: bT1OrsUUoSFZeOQ2r8iA, Data: {'VENTAJA': 12, 'HOLE': 10, 'YDS': 307, 'PAR': 4}
- Hole Document ID: dhxm8xL3O1w0M0BIeDE8, Data: {'VENTAJA': 6, 'HOLE': 12, 'YDS': 327, 'PAR': 4}
- Hole Document ID: ivVpTbPgH7lfRiRkWr5O, Data: {'VENTAJA': 16, 'HOLE': 16, 'YDS': 127, 'PAR': 3}
- Hole Document ID: knE4Nq8SqbaB2aetlFGv, Data: {'VENTAJA': 15, 'HOLE': 5, 'YDS': 328, 'PAR': 4}
- Hole Document ID: nLlxOYCgssEKSjiBkO7P, Data: {'VENTAJA': 17, 'HOLE': 7, 'YDS': 472, 'PAR': 5}
- Hole Document ID: sxt2Q7t4nRXWhseCyFFm, Data: {'VENTAJA': 9, 'HOLE': 9, 'YDS': 360, 'PAR': 4}
- Hole Document ID: tBkYrnoGArHWN9WakvnN, Data: {'VENTAJA': 11, 'HOLE': 1, 'YDS': 316, 'PAR': 4}
- Hole Document ID: tFEl6aKLDMfZJj6qpOVU, Data: {'VENTAJA': 2, 'HOLE': 15, 'YDS': 415, 'PAR': 4}
- Hole Document ID: ugVNEdvJuQjLi9oSt4HD, Data: {'VENTAJA': 4, 'HOLE': 17, 'YDS': 361, 'PAR': 4}

Course Document ID: ARRAYANES_AZUL
Course Data: {'TEE': 'AZUL', 'CC': 'ARRAYANES'}
Holes Subcollection Data:
- Hole Document ID: 0AkyqYD31Aopfz487J2Z, Data: {'VENTAJA': 8, 'HOLE': 8, 'YDS': 214, 'PAR': 3}
- Hole Document ID: 4AULUgTkGDqJujLRK6bL, Data: {'VENTAJA': 1, 'HOLE': 14, 'YDS': 433, 'PAR': 4}
- Hole Document ID: 4yhuclTsY8HvP1nSxgjt, Data: {'VENTAJA': 15, 'HOLE': 18, 'YDS': 373, 'PAR': 4}
- Hole Document ID: 520tOclGOJ9sAK7Sdfga, Data: {'VENTAJA': 6, 'HOLE': 3, 'YDS': 538, 'PAR': 5}
- Hole Document ID: 65JYoYf7cRpqUOWTLl9z, Data: {'VENTAJA': 12, 'HOLE': 9, 'YDS': 561, 'PAR': 5}
- Hole Document ID: AdlZtVSTIuKGsXLX7zXC, Data: {'VENTAJA': 14, 'HOLE': 2, 'YDS': 377, 'PAR': 4}
- Hole Document ID: GDbqbFQALGV6vfws2Eda, Data: {'VENTAJA': 5, 'HOLE': 16, 'YDS': 399, 'PAR': 4}
- Hole Document ID: I13nfQv0mGk9BeJHug5X, Data: {'VENTAJA': 17, 'HOLE': 10, 'YDS': 539, 'PAR': 5}
- Hole Document ID: Xu0etrX2o1xQDy6IZPvA, Data: {'VENTAJA': 7, 'HOLE': 11, 'YDS': 190, 'PAR': 3}
- Hole Document ID: YHrHIZyGxP0tVOAiDCkW, Data: {'VENTAJA': 10, 'HOLE': 5, 'YDS': 188, 'PAR': 3}
- Hole Document ID: ZFCQvf5JXuELD81CvVWD, Data: {'VENTAJA': 18, 'HOLE': 1, 'YDS': 373, 'PAR': 4}
- Hole Document ID: ZiahC2Bpb3Cofv4uWyG0, Data: {'VENTAJA': 3, 'HOLE': 12, 'YDS': 416, 'PAR': 4}
- Hole Document ID: a4DgYcYsaqE6ISnC1fRx, Data: {'VENTAJA': 13, 'HOLE': 17, 'YDS': 216, 'PAR': 3}
- Hole Document ID: a9osKqZXOxSte5HED2Ql, Data: {'VENTAJA': 11, 'HOLE': 15, 'YDS': 407, 'PAR': 4}
- Hole Document ID: g8xNJuCLY7NMr7ln4Dcf, Data: {'VENTAJA': 4, 'HOLE': 7, 'YDS': 438, 'PAR': 4}
- Hole Document ID: l3G1NqrDgX4XU9e2jtEz, Data: {'VENTAJA': 9, 'HOLE': 13, 'YDS': 585, 'PAR': 5}
- Hole Document ID: pXECH1qCDlBs2xwPGrCr, Data: {'VENTAJA': 2, 'HOLE': 6, 'YDS': 431, 'PAR': 4}
- Hole Document ID: uDDtY7o1KayuF45tkCPF, Data: {'VENTAJA': 16, 'HOLE': 4, 'YDS': 350, 'PAR': 4}

## Summary:

### Data Analysis Key Findings

*   The data from the `df_yardage` DataFrame was successfully restructured, grouping information by course and tee.
*   A nested dictionary structure was created, where each key represents a unique course and tee combination (e.g., 'APOSENTOS\_AZUL'), containing course/tee details and a list of hole data.
*   The restructured data was successfully uploaded to Firebase Firestore.
*   Documents were created in the 'courses' collection using the course and tee combination as the document ID.
*   Each course document contains a 'holes' subcollection.
*   Each hole's data ('VENTAJA', 'HOLE', 'YDS', 'PAR') was added as a separate document within the corresponding course's 'holes' subcollection.

### Insights or Next Steps

*   The structured data in Firestore is now ready to be queried for applications requiring course and hole-specific yardage information.
*   Consider adding indexing to the 'courses' and 'holes' collections in Firestore to optimize query performance.

**Reasoning**:
Iterate through the restructured data and upload each hole to its corresponding course document's 'holes' subcollection, using the 'HOLE' value as the document ID.

In [17]:
collection_ref = db.collection('courses')

for course_key, course_data in courses_data.items():
    course_doc_ref = collection_ref.document(course_key)

    # Create a subcollection 'holes' for each course document
    holes_collection_ref = course_doc_ref.collection('holes')
    for hole in course_data['holes']:
        # Use the 'HOLE' number as the document ID
        hole_doc_ref = holes_collection_ref.document(str(hole['HOLE']))
        # Add each hole as a document in the 'holes' subcollection
        hole_doc_ref.set(hole)

print("Data upload to Firestore with hole numbers as document IDs initiated.")

Data upload to Firestore with hole numbers as document IDs initiated.

## Verify structured upload

### Subtask:
Optionally, add code to verify that the data was successfully uploaded with the desired structure.

**Reasoning**:
Retrieve a few documents from the 'courses' collection and their 'holes' subcollections to verify the data structure and content in Firestore.

In [18]:
# Select a few representative documents to verify
course_keys_to_verify = list(courses_data.keys())[:3] # Verify the first 3 courses

print("Verifying uploaded data structure:")

for course_key in course_keys_to_verify:
    course_doc_ref = db.collection('courses').document(course_key)
    course_doc = course_doc_ref.get()

    if course_doc.exists:
        print(f"\nCourse Document ID: {course_doc.id}")
        print(f"Course Data: {course_doc.to_dict()}")

        holes_collection_ref = course_doc_ref.collection('holes')
        holes_stream = holes_collection_ref.stream()

        print("Holes Subcollection Data:")
        for hole_doc in holes_stream:
            print(f"- Hole Document ID: {hole_doc.id}, Data: {hole_doc.to_dict()}")
    else:
        print(f"\nCourse Document with ID {course_key} not found.")

Verifying uploaded data structure:

Course Document with ID APOSENTOS_AZUL not found.

Course Document with ID APOSENTOS_BLANCA not found.

Course Document with ID ARRAYANES_AZUL not found.

**Reasoning**:
Iterate through the restructured data and upload each course as a document to the 'courses' collection, using the course and tee combination as the document ID. Then, within each course document, create a 'holes' subcollection and add each hole as a document, using the 'HOLE' value as the document ID.

In [19]:
collection_ref = db.collection('courses')

for course_key, course_data in courses_data.items():
    course_doc_ref = collection_ref.document(course_key)

    # Create or update the course document with course and tee info
    course_doc_ref.set({
        'CC': course_data['CC'],
        'TEE': course_data['TEE']
    })

    # Create a subcollection 'holes' for each course document
    holes_collection_ref = course_doc_ref.collection('holes')
    for hole in course_data['holes']:
        # Use the 'HOLE' number as the document ID
        hole_doc_ref = holes_collection_ref.document(str(hole['HOLE']))
        # Add each hole as a document in the 'holes' subcollection
        hole_doc_ref.set(hole)

print("Data upload to Firestore with course names as document IDs and hole numbers as subcollection document IDs initiated.")

Data upload to Firestore with course names as document IDs and hole numbers as subcollection document IDs initiated.

## Verify structured upload

### Subtask:
Optionally, add code to verify that the data was successfully uploaded with the desired structure.

**Reasoning**:
Retrieve a few documents from the 'courses' collection and their 'holes' subcollections to verify the data structure and content in Firestore.

In [20]:
# Select a few representative documents to verify
course_keys_to_verify = list(courses_data.keys())[:3] # Verify the first 3 courses

print("Verifying uploaded data structure:")

for course_key in course_keys_to_verify:
    course_doc_ref = db.collection('courses').document(course_key)
    course_doc = course_doc_ref.get()

    if course_doc.exists:
        print(f"\nCourse Document ID: {course_doc.id}")
        print(f"Course Data: {course_doc.to_dict()}")

        holes_collection_ref = course_doc_ref.collection('holes')
        holes_stream = holes_collection_ref.stream()

        print("Holes Subcollection Data:")
        for hole_doc in holes_stream:
            print(f"- Hole Document ID: {hole_doc.id}, Data: {hole_doc.to_dict()}")
    else:
        print(f"\nCourse Document with ID {course_key} not found.")

Verifying uploaded data structure:

Course Document ID: APOSENTOS_AZUL
Course Data: {'TEE': 'AZUL', 'CC': 'APOSENTOS'}
Holes Subcollection Data:
- Hole Document ID: 1, Data: {'VENTAJA': 11, 'HOLE': 1, 'YDS': 316, 'PAR': 4}
- Hole Document ID: 10, Data: {'VENTAJA': 12, 'HOLE': 10, 'YDS': 344, 'PAR': 4}
- Hole Document ID: 11, Data: {'VENTAJA': 8, 'HOLE': 11, 'YDS': 190, 'PAR': 3}
- Hole Document ID: 12, Data: {'VENTAJA': 6, 'HOLE': 12, 'YDS': 337, 'PAR': 4}
- Hole Document ID: 13, Data: {'VENTAJA': 14, 'HOLE': 13, 'YDS': 173, 'PAR': 3}
- Hole Document ID: 14, Data: {'VENTAJA': 10, 'HOLE': 14, 'YDS': 566, 'PAR': 5}
- Hole Document ID: 15, Data: {'VENTAJA': 2, 'HOLE': 15, 'YDS': 440, 'PAR': 4}
- Hole Document ID: 16, Data: {'VENTAJA': 16, 'HOLE': 16, 'YDS': 147, 'PAR': 3}
- Hole Document ID: 17, Data: {'VENTAJA': 4, 'HOLE': 17, 'YDS': 383, 'PAR': 4}
- Hole Document ID: 18, Data: {'VENTAJA': 18, 'HOLE': 18, 'YDS': 475, 'PAR': 5}
- Hole Document ID: 2, Data: {'VENTAJA': 13, 'HOLE': 2, 'YDS': 519, 'PAR': 5}
- Hole Document ID: 3, Data: {'VENTAJA': 5, 'HOLE': 3, 'YDS': 173, 'PAR': 3}
- Hole Document ID: 4, Data: {'VENTAJA': 1, 'HOLE': 4, 'YDS': 480, 'PAR': 4}
- Hole Document ID: 5, Data: {'VENTAJA': 15, 'HOLE': 5, 'YDS': 362, 'PAR': 4}
- Hole Document ID: 6, Data: {'VENTAJA': 7, 'HOLE': 6, 'YDS': 214, 'PAR': 3}
- Hole Document ID: 7, Data: {'VENTAJA': 17, 'HOLE': 7, 'YDS': 483, 'PAR': 5}
- Hole Document ID: 8, Data: {'VENTAJA': 3, 'HOLE': 8, 'YDS': 424, 'PAR': 4}
- Hole Document ID: 9, Data: {'VENTAJA': 9, 'HOLE': 9, 'YDS': 400, 'PAR': 4}

Course Document ID: APOSENTOS_BLANCA
Course Data: {'TEE': 'BLANCA', 'CC': 'APOSENTOS'}
Holes Subcollection Data:
- Hole Document ID: 1, Data: {'VENTAJA': 11, 'HOLE': 1, 'YDS': 316, 'PAR': 4}
- Hole Document ID: 10, Data: {'VENTAJA': 12, 'HOLE': 10, 'YDS': 307, 'PAR': 4}
- Hole Document ID: 11, Data: {'VENTAJA': 8, 'HOLE': 11, 'YDS': 178, 'PAR': 3}
- Hole Document ID: 12, Data: {'VENTAJA': 6, 'HOLE': 12, 'YDS': 327, 'PAR': 4}
- Hole Document ID: 13, Data: {'VENTAJA': 14, 'HOLE': 13, 'YDS': 159, 'PAR': 3}
- Hole Document ID: 14, Data: {'VENTAJA': 10, 'HOLE': 14, 'YDS': 509, 'PAR': 5}
- Hole Document ID: 15, Data: {'VENTAJA': 2, 'HOLE': 15, 'YDS': 415, 'PAR': 4}
- Hole Document ID: 16, Data: {'VENTAJA': 16, 'HOLE': 16, 'YDS': 127, 'PAR': 3}
- Hole Document ID: 17, Data: {'VENTAJA': 4, 'HOLE': 17, 'YDS': 361, 'PAR': 4}
- Hole Document ID: 18, Data: {'VENTAJA': 18, 'HOLE': 18, 'YDS': 475, 'PAR': 5}
- Hole Document ID: 2, Data: {'VENTAJA': 13, 'HOLE': 2, 'YDS': 489, 'PAR': 5}
- Hole Document ID: 3, Data: {'VENTAJA': 5, 'HOLE': 3, 'YDS': 145, 'PAR': 3}
- Hole Document ID: 4, Data: {'VENTAJA': 1, 'HOLE': 4, 'YDS': 421, 'PAR': 4}
- Hole Document ID: 5, Data: {'VENTAJA': 15, 'HOLE': 5, 'YDS': 328, 'PAR': 4}
- Hole Document ID: 6, Data: {'VENTAJA': 7, 'HOLE': 6, 'YDS': 183, 'PAR': 3}
- Hole Document ID: 7, Data: {'VENTAJA': 17, 'HOLE': 7, 'YDS': 472, 'PAR': 5}
- Hole Document ID: 8, Data: {'VENTAJA': 3, 'HOLE': 8, 'YDS': 410, 'PAR': 4}
- Hole Document ID: 9, Data: {'VENTAJA': 9, 'HOLE': 9, 'YDS': 360, 'PAR': 4}

Course Document ID: ARRAYANES_AZUL
Course Data: {'TEE': 'AZUL', 'CC': 'ARRAYANES'}
Holes Subcollection Data:
- Hole Document ID: 1, Data: {'VENTAJA': 18, 'HOLE': 1, 'YDS': 373, 'PAR': 4}
- Hole Document ID: 10, Data: {'VENTAJA': 17, 'HOLE': 10, 'YDS': 539, 'PAR': 5}
- Hole Document ID: 11, Data: {'VENTAJA': 7, 'HOLE': 11, 'YDS': 190, 'PAR': 3}
- Hole Document ID: 12, Data: {'VENTAJA': 3, 'HOLE': 12, 'YDS': 416, 'PAR': 4}
- Hole Document ID: 13, Data: {'VENTAJA': 9, 'HOLE': 13, 'YDS': 585, 'PAR': 5}
- Hole Document ID: 14, Data: {'VENTAJA': 1, 'HOLE': 14, 'YDS': 433, 'PAR': 4}
- Hole Document ID: 15, Data: {'VENTAJA': 11, 'HOLE': 15, 'YDS': 407, 'PAR': 4}
- Hole Document ID: 16, Data: {'VENTAJA': 5, 'HOLE': 16, 'YDS': 399, 'PAR': 4}
- Hole Document ID: 17, Data: {'VENTAJA': 13, 'HOLE': 17, 'YDS': 216, 'PAR': 3}
- Hole Document ID: 18, Data: {'VENTAJA': 15, 'HOLE': 18, 'YDS': 373, 'PAR': 4}
- Hole Document ID: 2, Data: {'VENTAJA': 14, 'HOLE': 2, 'YDS': 377, 'PAR': 4}
- Hole Document ID: 3, Data: {'VENTAJA': 6, 'HOLE': 3, 'YDS': 538, 'PAR': 5}
- Hole Document ID: 4, Data: {'VENTAJA': 16, 'HOLE': 4, 'YDS': 350, 'PAR': 4}
- Hole Document ID: 5, Data: {'VENTAJA': 10, 'HOLE': 5, 'YDS': 188, 'PAR': 3}
- Hole Document ID: 6, Data: {'VENTAJA': 2, 'HOLE': 6, 'YDS': 431, 'PAR': 4}
- Hole Document ID: 7, Data: {'VENTAJA': 4, 'HOLE': 7, 'YDS': 438, 'PAR': 4}
- Hole Document ID: 8, Data: {'VENTAJA': 8, 'HOLE': 8, 'YDS': 214, 'PAR': 3}
- Hole Document ID: 9, Data: {'VENTAJA': 12, 'HOLE': 9, 'YDS': 561, 'PAR': 5}

## Summary:

### Data Analysis Key Findings

* The data from the `df_yardage` DataFrame was successfully restructured, grouping information by course and tee.
* A nested dictionary structure was created, where each key represents a unique course and tee combination (e.g., 'APOSENTOS\_AZUL'), containing course/tee details and a list of hole data.
* The restructured data was successfully uploaded to Firebase Firestore.
* Documents were created in the 'courses' collection using the course and tee combination as the document ID.
* Each course document contains a 'holes' subcollection.
* Each hole's data ('VENTAJA', 'HOLE', 'YDS', 'PAR') was added as a separate document within the corresponding course's 'holes' subcollection.

### Insights or Next Steps

* The structured data in Firestore is now ready to be queried for applications requiring course and hole-specific yardage information.
* Consider adding indexing to the 'courses' and 'holes' collections in Firestore to optimize query performance.

# Task
Update user data in the 'users' collection in Firebase using the data from "/content/drive/MyDrive/DNASHOT2/MASTER-FIREBASE.xlsx", matching users by their existing UIDs.

## Load the new user data

### Subtask:
Load the data from "/content/drive/MyDrive/DNASHOT2/MASTER-FIREBASE.xlsx" into a pandas DataFrame.

**Reasoning**:
Load the data from the specified Excel file path into a pandas DataFrame and display the first 5 rows along with the column information.

In [21]:
file_path = "/content/drive/MyDrive/DNASHOT2/MASTER-FIREBASE.xlsx"
df = pd.read_excel(file_path)

display(df.head())
display(df.info())

          CC   TEE  liminf A D  limsup  HDCP
0  APOSENTOS  5982    -5.0   A    -4.9    -9
1  APOSENTOS  5982    -4.8   A    -4.1    -8
2  APOSENTOS  5982    -4.0   A    -3.2    -7
3  APOSENTOS  5982    -3.1   A    -2.4    -6
4  APOSENTOS  5982    -2.3   A    -1.5    -5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2807 entries, 0 to 2806
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CC      2807 non-null   object
 1   TEE     2807 non-null   int64
 2   liminf  2807 non-null   float64
 3   A D     2807 non-null   object
 4   limsup  2807 non-null   float64
 5   HDCP    2807 non-null   int64
dtypes: float64(2), int64(2), object(2)
memory usage: 131.7+ KB

None

## Retrieve existing user data from firebase

### Subtask:
Read the existing user documents from the 'users' collection in Firebase, making sure to get their UIDs.

**Reasoning**:
Get a reference to the 'users' collection, retrieve all documents, and store their data and UIDs in a list of dictionaries.

In [22]:
users_ref = db.collection('users')
users_docs = users_ref.stream()

existing_users = []
for doc in users_docs:
    user_data = doc.to_dict()
    user_data['uid'] = doc.id  # Add the document ID (UID) to the data
    existing_users.append(user_data)

print(f"Retrieved {len(existing_users)} existing user documents.")

Retrieved 2 existing user documents.

## Prepare data for merging

### Subtask:
Ensure that both the new data and the existing Firebase data are in a format that allows for easy merging based on the UIDs.

**Reasoning**:
Convert the existing users data into a DataFrame and rename the UID column to match the new data for merging.

In [23]:
df_existing_users = pd.DataFrame(existing_users)
df_existing_users = df_existing_users.rename(columns={'uid': 'TEE'})

display(df_existing_users.head())

  fedecol  nick                    nombre    tee                           TEE
0           TEO        MATEO LISOCKI CALA  White  AUYyVUqkcURbPnDlK8jRsUdxX7v2
1          NEIF  SANTIAGO MOLINA CARDENAS  White  x5QNFTSBu2SNytbUCNvFYByoMr32

## Merge data

### Subtask:
Merge the new data from the DataFrame with the existing Firebase data using the UIDs as the key.

**Reasoning**:
Merge the new data (df) with the existing user data (df_existing_users) based on the 'TEE' column (which represents the UIDs) to combine the datasets.

In [24]:
merged_df = pd.merge(df, df_existing_users, on='TEE', how='inner')

display(merged_df.head())

ValueError: You are trying to merge on int64 and object columns for key 'TEE'. If you wish to proceed you should use pd.concat

**Reasoning**:
The merge failed because the 'TEE' columns in the two dataframes have different data types (int64 and object). Convert the 'TEE' column in `df` to object type to match `df_existing_users` before merging.

In [25]:
df['TEE'] = df['TEE'].astype(str)
merged_df = pd.merge(df, df_existing_users, on='TEE', how='inner')

display(merged_df.head())

Empty DataFrame
Columns: [CC, TEE, liminf, A D, limsup, HDCP, fedecol, nick, nombre, tee]
Index: []

## Summary:

### Data Analysis Key Findings

*   Successfully loaded the new user data from "/content/drive/MyDrive/DNASHOT2/MASTER-FIREBASE.xlsx" into a pandas DataFrame (`df`) with 2807 rows and 6 columns.
*   Successfully retrieved existing user data from Firebase's 'users' collection, resulting in 2 user documents.
*   Converted the existing Firebase user data into a pandas DataFrame (`df_existing_users`) and renamed the 'uid' column to 'TEE' for merging purposes.
*   Attempting to merge the new data (`df`) and existing user data (`df_existing_users`) on the 'TEE' column resulted in an empty DataFrame, indicating no matching 'TEE' values (intended as UIDs) between the two datasets.

### Insights or Next Steps

*   Investigate the 'TEE' column in the new data (`df`) to determine if it contains the correct UIDs or if there is an alternative column that represents the user identifiers needed to match with the Firebase UIDs.
*   If the new data does not contain the Firebase UIDs, explore alternative methods to link the new data to existing users in Firebase, potentially using other common attributes if available.

# Task
Upload the data from "/content/drive/MyDrive/DNASHOT2/ALLDATA.xlsx" to the 'users' collection in Firebase. Use the UID from the data as the document ID for each user. Within each user document, create a subcollection named 'CC'. Within the 'CC' subcollection, add the relevant data from the Excel file, including hole information. Ensure that the hole information is organized by hole number (1-18) for easy consultation.

## Load the new data

### Subtask:
Load the data from "/content/drive/MyDrive/DNASHOT2/ALLDATA.xlsx" into a pandas DataFrame.

**Reasoning**:
Load the data from the specified Excel file path into a pandas DataFrame and display the first 5 rows along with the column information.

In [26]:
file_path = "/content/drive/MyDrive/DNASHOT2/ALLDATA.xlsx"
df_all_data = pd.read_excel(file_path)

display(df_all_data.head())
display(df_all_data.info())

,ROUNDS,SCORECARD DATE,CC,TEE,HOLE,YDS,HDCP,PAR,SCORE,PUTT,DD,DDTYPE,PINDIST,1STPU,UID,ESC
0,1,2023-04-07,GUAY#2,BLANCA,1,554,6,5,4,1,NaN,NaN,185.0,NaN,AUYyVUqkcURbPnDlK8jRsUdxX7v2,4
1,1,2023-04-07,GUAY#2,BLANCA,2,427,2,4,4,1,NaN,NaN,142.0,NaN,AUYyVUqkcURbPnDlK8jRsUdxX7v2,4
2,1,2023-04-07,GUAY#2,BLANCA,3,370,14,4,5,2,NaN,NaN,123.0,NaN,AUYyVUqkcURbPnDlK8jRsUdxX7v2,5
3,1,2023-04-07,GUAY#2,BLANCA,4,167,16,3,4,1,NaN,NaN,NaN,NaN,AUYyVUqkcURbPnDlK8jRsUdxX7v2,4
4,1,2023-04-07,GUAY#2,BLANCA,5,397,4,4,8,3,NaN,NaN,79.0,NaN,AUYyVUqkcURbPnDlK8jRsUdxX7v2,6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2952 entries, 0 to 2951
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ROUNDS          2952 non-null   int64
 1   SCORECARD DATE  2952 non-null   datetime64[ns]
 2   CC              2952 non-null   object
 3   TEE             2952 non-null   object
 4   HOLE            2952 non-null   int64
 5   YDS             2952 non-null   int64
 6   HDCP            2952 non-null   int64
 7   PAR             2952 non-null   int64
 8   SCORE           2952 non-null   int64
 9   PUTT            2952 non-null   int64
 10  DD              1785 non-null   float64
 11  DDTYPE          1465 non-null   object
 12  PINDIST         2243 non-null   float64
 13  1STPU           2008 non-null   float64
 14  UID             2952 non-null   object
 15  ESC             2952 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(8), object(4)
memory usage: 369.1+ KB

None

## Prepare data for structured upload

### Subtask:
Restructure the DataFrame to group data by user (UID), and then prepare it for upload with nested 'CC' subcollections and hole data within those.

**Reasoning**:
Group the DataFrame by 'UID' and then iterate through the groups to create a nested structure for uploading to Firestore, with each user as a document and their course and hole data in nested structures within.

In [27]:
users_data_structured = {}

grouped_by_user = df_all_data.groupby('UID')

for uid, user_group in grouped_by_user:
    users_data_structured[uid] = {
        'courses': {}
    }
    # Group by course and tee within each user's data
    grouped_by_course_tee = user_group.groupby(['CC', 'TEE'])
    for (cc, tee), course_tee_group in grouped_by_course_tee:
        course_tee_key = f"{cc}_{tee}"
        users_data_structured[uid]['courses'][course_tee_key] = {
            'CC': cc,
            'TEE': tee,
            'holes': {}
        }
        # Iterate through holes within each course/tee
        for index, hole_row in course_tee_group.iterrows():
            hole_number = str(hole_row['HOLE'])
            users_data_structured[uid]['courses'][course_tee_key]['holes'][hole_number] = {
                'HOLE': hole_row['HOLE'],
                'PAR': hole_row['PAR'],
                'YDS': hole_row['YDS'],
                'SCORE': hole_row['SCORE'],
                'PUTT': hole_row['PUTT'],
                'DD': hole_row['DD'],
                'DDTYPE': hole_row['DDTYPE'],
                'PINDIST': hole_row['PINDIST'],
                '1STPU': hole_row['1STPU'],
                'ESC': hole_row['ESC']
            }

print(f"Prepared structured data for {len(users_data_structured)} users.")

Prepared structured data for 2 users.

## Upload structured data to firebase

### Subtask:
Write code to iterate through the restructured data and upload it to the 'users' collection, using the UID as the document ID, creating 'CC' subcollections, and adding hole data within those.

**Reasoning**:
Iterate through the restructured data and upload each user to the 'users' collection, using the UID as the document ID, creating 'CC' subcollections, and adding hole data within those, using the hole number as the document ID.

In [28]:
users_ref = db.collection('users')

for uid, user_data in users_data_structured.items():
    user_doc_ref = users_ref.document(uid)

    # Create a subcollection 'CC' for each user document
    cc_collection_ref = user_doc_ref.collection('CC')

    for course_tee_key, course_tee_data in user_data['courses'].items():
        # Create a document for each course/tee round in the 'CC' subcollection
        # Using a composite key for the document ID or generating a new one
        course_tee_doc_ref = cc_collection_ref.document(course_tee_key) # Using the composite key as document ID

        # Set the data for the course/tee document
        course_tee_doc_ref.set({
            'CC': course_tee_data['CC'],
            'TEE': course_tee_data['TEE']
        })

        # Create a subcollection 'holes' within the course/tee document
        holes_collection_ref = course_tee_doc_ref.collection('holes')

        for hole_number, hole_data in course_tee_data['holes'].items():
            # Create a document for each hole in the 'holes' subcollection
            hole_doc_ref = holes_collection_ref.document(hole_number) # Using the hole number as document ID
            hole_doc_ref.set(hole_data)

print("Structured data upload to Firebase initiated.")

Structured data upload to Firebase initiated.

**Reasoning**:
Verify that the data was successfully uploaded to Firestore with the desired structure by retrieving a few user documents, their 'CC' subcollections, and the 'holes' subcollections within those.

In [29]:
# Select a few representative UIDs to verify
uids_to_verify = list(users_data_structured.keys())[:2] # Verify the first 2 users

print("Verifying uploaded data structure:")

for uid in uids_to_verify:
    user_doc_ref = db.collection('users').document(uid)
    user_doc = user_doc_ref.get()

    if user_doc.exists:
        print(f"\nUser Document ID: {user_doc.id}")

        cc_collection_ref = user_doc_ref.collection('CC')
        cc_stream = cc_collection_ref.stream()

        print("CC Subcollection Data:")
        for cc_doc in cc_stream:
            print(f"- Course/Tee Document ID: {cc_doc.id}, Data: {cc_doc.to_dict()}")

            holes_collection_ref = cc_doc.reference.collection('holes')
            holes_stream = holes_collection_ref.stream()

            print("  Holes Subcollection Data:")
            for hole_doc in holes_stream:
                print(f"  - Hole Document ID: {hole_doc.id}, Data: {hole_doc.to_dict()}")
    else:
        print(f"\nUser Document with ID {uid} not found.")

Verifying uploaded data structure:

User Document with ID AUYyVUqkcURbPnDlK8jRsUdxX7v2 not found.

User Document with ID x5QNFTSBu2SNytbUCNvFYByoMr32 not found.

**Reasoning**:
The verification step showed that the user documents were not found. This indicates an issue with the previous upload attempt. Re-attempt the upload process, ensuring the correct collection and document references are used.

In [30]:
users_ref = db.collection('users')

for uid, user_data in users_data_structured.items():
    user_doc_ref = users_ref.document(uid)

    # Create or update the user document (optional, depending on whether user docs exist)
    # user_doc_ref.set({}) # Uncomment if you need to explicitly create user documents

    # Create a subcollection 'CC' for each user document
    cc_collection_ref = user_doc_ref.collection('CC')

    for course_tee_key, course_tee_data in user_data['courses'].items():
        # Create a document for each course/tee round in the 'CC' subcollection
        # Using a composite key for the document ID
        course_tee_doc_ref = cc_collection_ref.document(course_tee_key)

        # Set the data for the course/tee document
        course_tee_doc_ref.set({
            'CC': course_tee_data['CC'],
            'TEE': course_tee_data['TEE']
        })

        # Create a subcollection 'holes' within the course/tee document
        holes_collection_ref = course_tee_doc_ref.collection('holes')

        for hole_number, hole_data in course_tee_data['holes'].items():
            # Create a document for each hole in the 'holes' subcollection
            hole_doc_ref = holes_collection_ref.document(hole_number)
            hole_doc_ref.set(hole_data)

print("Structured data upload to Firebase re-initiated.")

Structured data upload to Firebase re-initiated.

**Reasoning**:
Verify that the data was successfully uploaded to Firestore with the desired structure by retrieving a few user documents, their 'CC' subcollections, and the 'holes' subcollections within those.

In [31]:
# Select a few representative UIDs to verify
uids_to_verify = list(users_data_structured.keys())[:2] # Verify the first 2 users

print("Verifying uploaded data structure:")

for uid in uids_to_verify:
    user_doc_ref = db.collection('users').document(uid)
    user_doc = user_doc_ref.get()

    if user_doc.exists:
        print(f"\nUser Document ID: {user_doc.id}")

        cc_collection_ref = user_doc_ref.collection('CC')
        cc_stream = cc_collection_ref.stream()

        print("CC Subcollection Data:")
        for cc_doc in cc_stream:
            print(f"- Course/Tee Document ID: {cc_doc.id}, Data: {cc_doc.to_dict()}")

            holes_collection_ref = cc_doc.reference.collection('holes')
            holes_stream = holes_collection_ref.stream()

            print("  Holes Subcollection Data:")
            for hole_doc in holes_stream:
                print(f"  - Hole Document ID: {hole_doc.id}, Data: {hole_doc.to_dict()}")
    else:
        print(f"\nUser Document with ID {uid} not found.")

Verifying uploaded data structure:

User Document with ID AUYyVUqkcURbPnDlK8jRsUdxX7v2 not found.

User Document with ID x5QNFTSBu2SNytbUCNvFYByoMr32 not found.

**Reasoning**:
The previous verification steps failed to find the user documents, indicating the data was not uploaded correctly. Re-attempt the upload process, explicitly creating the user document before creating subcollections to ensure the parent document exists.

In [32]:
users_ref = db.collection('users')

for uid, user_data in users_data_structured.items():
    user_doc_ref = users_ref.document(uid)

    # Explicitly create the user document
    user_doc_ref.set({}) # Create an empty document if it doesn't exist

    # Create a subcollection 'CC' for each user document
    cc_collection_ref = user_doc_ref.collection('CC')

    for course_tee_key, course_tee_data in user_data['courses'].items():
        # Create a document for each course/tee round in the 'CC' subcollection
        course_tee_doc_ref = cc_collection_ref.document(course_tee_key)

        # Set the data for the course/tee document
        course_tee_doc_ref.set({
            'CC': course_tee_data['CC'],
            'TEE': course_tee_data['TEE']
        })

        # Create a subcollection 'holes' within the course/tee document
        holes_collection_ref = course_tee_doc_ref.collection('holes')

        for hole_number, hole_data in course_tee_data['holes'].items():
            # Create a document for each hole in the 'holes' subcollection
            hole_doc_ref = holes_collection_ref.document(hole_number)
            hole_doc_ref.set(hole_data)

print("Structured data upload to Firebase re-initiated with explicit user document creation.")

Structured data upload to Firebase re-initiated with explicit user document creation.

**Reasoning**:
Verify that the data was successfully uploaded to Firestore with the desired structure by retrieving a few user documents, their 'CC' subcollections, and the 'holes' subcollections within those.

In [33]:
# Select a few representative UIDs to verify
uids_to_verify = list(users_data_structured.keys())[:2] # Verify the first 2 users

print("Verifying uploaded data structure:")

for uid in uids_to_verify:
    user_doc_ref = db.collection('users').document(uid)
    user_doc = user_doc_ref.get()

    if user_doc.exists:
        print(f"\nUser Document ID: {user_doc.id}")

        cc_collection_ref = user_doc_ref.collection('CC')
        cc_stream = cc_collection_ref.stream()

        print("CC Subcollection Data:")
        for cc_doc in cc_stream:
            print(f"- Course/Tee Document ID: {cc_doc.id}, Data: {cc_doc.to_dict()}")

            holes_collection_ref = cc_doc.reference.collection('holes')
            holes_stream = holes_collection_ref.stream()

            print("  Holes Subcollection Data:")
            for hole_doc in holes_stream:
                print(f"  - Hole Document ID: {hole_doc.id}, Data: {hole_doc.to_dict()}")
    else:
        print(f"\nUser Document with ID {uid} not found.")

Verifying uploaded data structure:

User Document ID: AUYyVUqkcURbPnDlK8jRsUdxX7v2
CC Subcollection Data:
- Course/Tee Document ID: ARRAYANES_BLANCA, Data: {'TEE': 'BLANCA', 'CC': 'ARRAYANES'}
  Holes Subcollection Data:
  - Hole Document ID: 1, Data: {'HOLE': 1, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 4, 'PINDIST': 50.0, 'SCORE': 5, '1STPU': 3.0, 'ESC': 5, 'YDS': 347, 'DD': 200.0}
  - Hole Document ID: 10, Data: {'HOLE': 10, 'DDTYPE': 'F', 'PUTT': 3, 'PAR': 5, 'PINDIST': 170.0, 'SCORE': 7, '1STPU': 8.0, 'ESC': 7, 'YDS': 513, 'DD': 119.0}
  - Hole Document ID: 11, Data: {'HOLE': 11, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 3, 'PINDIST': nan, 'SCORE': 6, '1STPU': 10.0, 'ESC': 5, 'YDS': 175, 'DD': nan}
  - Hole Document ID: 12, Data: {'HOLE': 12, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 150.0, 'SCORE': 5, '1STPU': 12.0, 'ESC': 5, 'YDS': 394, 'DD': 243.0}
  - Hole Document ID: 13, Data: {'HOLE': 13, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 5, 'PINDIST': 20.0, 'SCORE': 6, '1STPU': 3.0, 'ESC': 6, 'YDS': 550, 'DD': 233.0}
  - Hole Document ID: 14, Data: {'HOLE': 14, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 30.0, 'SCORE': 6, '1STPU': 8.0, 'ESC': 6, 'YDS': 419, 'DD': 270.0}
  - Hole Document ID: 15, Data: {'HOLE': 15, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 4, 'PINDIST': 25.0, 'SCORE': 5, '1STPU': 4.0, 'ESC': 5, 'YDS': 374, 'DD': 173.0}
  - Hole Document ID: 16, Data: {'HOLE': 16, 'DDTYPE': 'R', 'PUTT': 2, 'PAR': 4, 'PINDIST': 70.0, 'SCORE': 6, '1STPU': 5.0, 'ESC': 6, 'YDS': 382, 'DD': 200.0}
  - Hole Document ID: 17, Data: {'HOLE': 17, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 4, '1STPU': 2.0, 'ESC': 4, 'YDS': 194, 'DD': nan}
  - Hole Document ID: 18, Data: {'HOLE': 18, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 60.0, 'SCORE': 6, '1STPU': 3.0, 'ESC': 6, 'YDS': 361, 'DD': 280.0}
  - Hole Document ID: 2, Data: {'HOLE': 2, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 4, 'PINDIST': 78.0, 'SCORE': 4, '1STPU': 1.0, 'ESC': 4, 'YDS': 354, 'DD': 262.0}
  - Hole Document ID: 3, Data: {'HOLE': 3, 'DDTYPE': 'L', 'PUTT': 3, 'PAR': 5, 'PINDIST': 80.0, 'SCORE': 7, '1STPU': 7.0, 'ESC': 7, 'YDS': 511, 'DD': 222.0}
  - Hole Document ID: 4, Data: {'HOLE': 4, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 85.0, 'SCORE': 4, '1STPU': 6.0, 'ESC': 4, 'YDS': 333, 'DD': 254.0}
  - Hole Document ID: 5, Data: {'HOLE': 5, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 1.0, 'ESC': 3, 'YDS': 160, 'DD': nan}
  - Hole Document ID: 6, Data: {'HOLE': 6, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 4, 'PINDIST': 55.0, 'SCORE': 5, '1STPU': 2.0, 'ESC': 5, 'YDS': 392, 'DD': 247.0}
  - Hole Document ID: 7, Data: {'HOLE': 7, 'DDTYPE': 'F', 'PUTT': 3, 'PAR': 4, 'PINDIST': 10.0, 'SCORE': 7, '1STPU': 5.0, 'ESC': 6, 'YDS': 410, 'DD': 225.0}
  - Hole Document ID: 8, Data: {'HOLE': 8, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 5, '1STPU': 2.0, 'ESC': 5, 'YDS': 199, 'DD': nan}
  - Hole Document ID: 9, Data: {'HOLE': 9, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 30.0, 'SCORE': 5, '1STPU': 3.0, 'ESC': 5, 'YDS': 534, 'DD': 214.0}
- Course/Tee Document ID: BRICEÑO_BLANCA, Data: {'TEE': 'BLANCA', 'CC': 'BRICEÑO'}
  Holes Subcollection Data:
  - Hole Document ID: 1, Data: {'HOLE': 1, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 4, 'PINDIST': 46.0, 'SCORE': 8, '1STPU': nan, 'ESC': 6, 'YDS': 407, 'DD': 222.0}
  - Hole Document ID: 10, Data: {'HOLE': 10, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 56.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 473, 'DD': 250.0}
  - Hole Document ID: 11, Data: {'HOLE': 11, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 4, 'PINDIST': 30.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 334, 'DD': 273.0}
  - Hole Document ID: 12, Data: {'HOLE': 12, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 4, 'PINDIST': 139.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 298, 'DD': 159.0}
  - Hole Document ID: 13, Data: {'HOLE': 13, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 3, 'PINDIST': nan, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 176, 'DD': nan}
  - Hole Document ID: 14, Data: {'HOLE': 14, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 90.0, 'SCORE': 7, '1STPU': nan, 'ESC': 7, 'YDS': 541, 'DD': 158.0}
  - Hole Document ID: 15, Data: {'HOLE': 15, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': nan, 'ESC': 3, 'YDS': 192, 'DD': nan}
  - Hole Document ID: 16, Data: {'HOLE': 16, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 4, 'PINDIST': 87.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 435, 'DD': nan}
  - Hole Document ID: 17, Data: {'HOLE': 17, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': nan, 'ESC': 3, 'YDS': 191, 'DD': nan}
  - Hole Document ID: 18, Data: {'HOLE': 18, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 136.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 544, 'DD': 230.0}
  - Hole Document ID: 2, Data: {'HOLE': 2, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 3, 'PINDIST': nan, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 200, 'DD': nan}
  - Hole Document ID: 3, Data: {'HOLE': 3, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 4, 'PINDIST': 23.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 292, 'DD': 246.0}
  - Hole Document ID: 4, Data: {'HOLE': 4, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': nan, 'ESC': 3, 'YDS': 170, 'DD': nan}
  - Hole Document ID: 5, Data: {'HOLE': 5, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 5, 'PINDIST': 186.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 480, 'DD': 294.0}
  - Hole Document ID: 6, Data: {'HOLE': 6, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 4, 'PINDIST': 52.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 364, 'DD': 261.0}
  - Hole Document ID: 7, Data: {'HOLE': 7, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 4, 'PINDIST': 75.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 439, 'DD': 289.0}
  - Hole Document ID: 8, Data: {'HOLE': 8, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 4, 'PINDIST': 182.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 364, 'DD': nan}
  - Hole Document ID: 9, Data: {'HOLE': 9, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 112.0, 'SCORE': 8, '1STPU': nan, 'ESC': 7, 'YDS': 561, 'DD': nan}
- Course/Tee Document ID: BRITANIA_BLANCA, Data: {'TEE': 'BLANCA', 'CC': 'BRITANIA'}
  Holes Subcollection Data:
  - Hole Document ID: 1, Data: {'HOLE': 1, 'DDTYPE': 'R', 'PUTT': 2, 'PAR': 4, 'PINDIST': 150.0, 'SCORE': 4, '1STPU': 10.0, 'ESC': 4, 'YDS': 373, 'DD': 237.0}
  - Hole Document ID: 10, Data: {'HOLE': 10, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 30.0, 'SCORE': 6, '1STPU': 4.0, 'ESC': 6, 'YDS': 373, 'DD': 222.0}
  - Hole Document ID: 11, Data: {'HOLE': 11, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 3, 'PINDIST': nan, 'SCORE': 4, '1STPU': 7.0, 'ESC': 4, 'YDS': 134, 'DD': nan}
  - Hole Document ID: 12, Data: {'HOLE': 12, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 100.0, 'SCORE': 6, '1STPU': 6.0, 'ESC': 6, 'YDS': 569, 'DD': 220.0}
  - Hole Document ID: 13, Data: {'HOLE': 13, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 4, '1STPU': 7.0, 'ESC': 4, 'YDS': 186, 'DD': nan}
  - Hole Document ID: 14, Data: {'HOLE': 14, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 4, 'PINDIST': 10.0, 'SCORE': 4, '1STPU': 1.0, 'ESC': 4, 'YDS': 349, 'DD': 235.0}
  - Hole Document ID: 15, Data: {'HOLE': 15, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 5, 'PINDIST': 10.0, 'SCORE': 6, '1STPU': 2.0, 'ESC': 6, 'YDS': 535, 'DD': 224.0}
  - Hole Document ID: 16, Data: {'HOLE': 16, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 2.0, 'ESC': 3, 'YDS': 183, 'DD': nan}
  - Hole Document ID: 17, Data: {'HOLE': 17, 'DDTYPE': 'R', 'PUTT': 2, 'PAR': 4, 'PINDIST': 30.0, 'SCORE': 6, '1STPU': 5.0, 'ESC': 6, 'YDS': 338, 'DD': 250.0}
  - Hole Document ID: 18, Data: {'HOLE': 18, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 4, '1STPU': 3.0, 'ESC': 4, 'YDS': 164, 'DD': nan}
  - Hole Document ID: 2, Data: {'HOLE': 2, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 4, '1STPU': 2.0, 'ESC': 4, 'YDS': 134, 'DD': nan}
  - Hole Document ID: 3, Data: {'HOLE': 3, 'DDTYPE': 'L', 'PUTT': 1, 'PAR': 5, 'PINDIST': 45.0, 'SCORE': 6, '1STPU': 1.0, 'ESC': 6, 'YDS': 569, 'DD': 215.0}
  - Hole Document ID: 4, Data: {'HOLE': 4, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 5, '1STPU': 1.0, 'ESC': 5, 'YDS': 186, 'DD': nan}
  - Hole Document ID: 5, Data: {'HOLE': 5, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 4, 'PINDIST': 50.0, 'SCORE': 5, '1STPU': 3.0, 'ESC': 5, 'YDS': 349, 'DD': 227.0}
  - Hole Document ID: 6, Data: {'HOLE': 6, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 5, 'PINDIST': 45.0, 'SCORE': 6, '1STPU': 8.0, 'ESC': 6, 'YDS': 535, 'DD': 232.0}
  - Hole Document ID: 7, Data: {'HOLE': 7, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 2, '1STPU': 1.0, 'ESC': 2, 'YDS': 183, 'DD': nan}
  - Hole Document ID: 8, Data: {'HOLE': 8, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 169.0, 'SCORE': 4, '1STPU': 7.0, 'ESC': 4, 'YDS': 338, 'DD': 216.0}
  - Hole Document ID: 9, Data: {'HOLE': 9, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 1.0, 'ESC': 3, 'YDS': 164, 'DD': nan}
- Course/Tee Document ID: CARMEL_BLANCA, Data: {'TEE': 'BLANCA', 'CC': 'CARMEL'}
  Holes Subcollection Data:
  - Hole Document ID: 1, Data: {'HOLE': 1, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 1.0, 'ESC': 3, 'YDS': 180, 'DD': nan}
  - Hole Document ID: 10, Data: {'HOLE': 10, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 4, 'PINDIST': 70.0, 'SCORE': 5, '1STPU': 14.0, 'ESC': 5, 'YDS': 389, 'DD': 183.0}
  - Hole Document ID: 11, Data: {'HOLE': 11, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 4, 'PINDIST': 65.0, 'SCORE': 7, '1STPU': 4.0, 'ESC': 6, 'YDS': 316, 'DD': 150.0}
  - Hole Document ID: 12, Data: {'HOLE': 12, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 5, '1STPU': 2.0, 'ESC': 5, 'YDS': 180, 'DD': nan}
  - Hole Document ID: 13, Data: {'HOLE': 13, 'DDTYPE': 'L', 'PUTT': 1, 'PAR': 4, 'PINDIST': 12.0, 'SCORE': 4, '1STPU': 1.0, 'ESC': 4, 'YDS': 380, 'DD': 220.0}
  - Hole Document ID: 14, Data: {'HOLE': 14, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 5, 'PINDIST': 18.0, 'SCORE': 5, '1STPU': 1.0, 'ESC': 5, 'YDS': 475, 'DD': 239.0}
  - Hole Document ID: 15, Data: {'HOLE': 15, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 2, '1STPU': 1.0, 'ESC': 2, 'YDS': 171, 'DD': nan}
  - Hole Document ID: 16, Data: {'HOLE': 16, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 20.0, 'SCORE': 6, '1STPU': 7.0, 'ESC': 6, 'YDS': 371, 'DD': 149.0}
  - Hole Document ID: 17, Data: {'HOLE': 17, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 50.0, 'SCORE': 6, '1STPU': 3.0, 'ESC': 6, 'YDS': 370, 'DD': 225.0}
  - Hole Document ID: 18, Data: {'HOLE': 18, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 4, 'PINDIST': 76.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 379, 'DD': 212.0}
  - Hole Document ID: 2, Data: {'HOLE': 2, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 1.0, 'ESC': 3, 'YDS': 181, 'DD': nan}
  - Hole Document ID: 3, Data: {'HOLE': 3, 'DDTYPE': 'S', 'PUTT': 2, 'PAR': 4, 'PINDIST': 25.0, 'SCORE': 5, '1STPU': 5.0, 'ESC': 5, 'YDS': 344, 'DD': 209.0}
  - Hole Document ID: 4, Data: {'HOLE': 4, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 45.0, 'SCORE': 8, '1STPU': 2.0, 'ESC': 6, 'YDS': 416, 'DD': 237.0}
  - Hole Document ID: 5, Data: {'HOLE': 5, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 65.0, 'SCORE': 6, '1STPU': 4.0, 'ESC': 6, 'YDS': 500, 'DD': 224.0}
  - Hole Document ID: 6, Data: {'HOLE': 6, 'DDTYPE': 'L', 'PUTT': 3, 'PAR': 5, 'PINDIST': 93.0, 'SCORE': 9, '1STPU': nan, 'ESC': 7, 'YDS': 558, 'DD': 253.0}
  - Hole Document ID: 7, Data: {'HOLE': 7, 'DDTYPE': 'L', 'PUTT': 1, 'PAR': 4, 'PINDIST': 18.0, 'SCORE': 5, '1STPU': 2.0, 'ESC': 5, 'YDS': 412, 'DD': 235.0}
  - Hole Document ID: 8, Data: {'HOLE': 8, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 120.0, 'SCORE': 4, '1STPU': 16.0, 'ESC': 4, 'YDS': 347, 'DD': 217.0}
  - Hole Document ID: 9, Data: {'HOLE': 9, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 193, 'DD': nan}
- Course/Tee Document ID: CORAL SPRINGS_BLANCA, Data: {'TEE': 'BLANCA', 'CC': 'CORAL SPRINGS'}
  Holes Subcollection Data:
  - Hole Document ID: 1, Data: {'HOLE': 1, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 115.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 495, 'DD': 200.0}
  - Hole Document ID: 10, Data: {'HOLE': 10, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 5.0, 'SCORE': 3, '1STPU': nan, 'ESC': 3, 'YDS': 495, 'DD': 219.0}
  - Hole Document ID: 11, Data: {'HOLE': 11, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': nan, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 495, 'DD': nan}
  - Hole Document ID: 12, Data: {'HOLE': 12, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 137.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 495, 'DD': 252.0}
  - Hole Document ID: 13, Data: {'HOLE': 13, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 90.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 495, 'DD': 66.0}
  - Hole Document ID: 14, Data: {'HOLE': 14, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 103.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 495, 'DD': 190.0}
  - Hole Document ID: 15, Data: {'HOLE': 15, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': nan, 'SCORE': 3, '1STPU': nan, 'ESC': 3, 'YDS': 495, 'DD': nan}
  - Hole Document ID: 16, Data: {'HOLE': 16, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 178.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 495, 'DD': 194.0}
  - Hole Document ID: 17, Data: {'HOLE': 17, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 70.0, 'SCORE': 7, '1STPU': nan, 'ESC': 7, 'YDS': 495, 'DD': 51.0}
  - Hole Document ID: 18, Data: {'HOLE': 18, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 130.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 495, 'DD': 185.0}
  - Hole Document ID: 2, Data: {'HOLE': 2, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': nan, 'SCORE': 3, '1STPU': nan, 'ESC': 3, 'YDS': 495, 'DD': nan}
  - Hole Document ID: 3, Data: {'HOLE': 3, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 99.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 495, 'DD': nan}
  - Hole Document ID: 4, Data: {'HOLE': 4, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 100.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 495, 'DD': 190.0}
  - Hole Document ID: 5, Data: {'HOLE': 5, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 66.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 495, 'DD': 149.0}
  - Hole Document ID: 6, Data: {'HOLE': 6, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 5, 'PINDIST': 78.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 495, 'DD': 212.0}
  - Hole Document ID: 7, Data: {'HOLE': 7, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': nan, 'SCORE': 3, '1STPU': nan, 'ESC': 3, 'YDS': 495, 'DD': nan}
  - Hole Document ID: 8, Data: {'HOLE': 8, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 5, 'PINDIST': 182.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 495, 'DD': 175.0}
  - Hole Document ID: 9, Data: {'HOLE': 9, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 5, 'PINDIST': nan, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 495, 'DD': nan}
- Course/Tee Document ID: CRANDON_BLANCA, Data: {'TEE': 'BLANCA', 'CC': 'CRANDON'}
  Holes Subcollection Data:
  - Hole Document ID: 1, Data: {'HOLE': 1, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 118.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': 190.0}
  - Hole Document ID: 10, Data: {'HOLE': 10, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 122.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': 238.0}
  - Hole Document ID: 11, Data: {'HOLE': 11, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 101.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': 225.0}
  - Hole Document ID: 12, Data: {'HOLE': 12, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': nan, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 463, 'DD': nan}
  - Hole Document ID: 13, Data: {'HOLE': 13, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 81.0, 'SCORE': 7, '1STPU': nan, 'ESC': 7, 'YDS': 463, 'DD': 222.0}
  - Hole Document ID: 14, Data: {'HOLE': 14, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 127.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': 230.0}
  - Hole Document ID: 15, Data: {'HOLE': 15, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 97.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': 221.0}
  - Hole Document ID: 16, Data: {'HOLE': 16, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 86.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': 189.0}
  - Hole Document ID: 17, Data: {'HOLE': 17, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': nan, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': nan}
  - Hole Document ID: 18, Data: {'HOLE': 18, 'DDTYPE': 'F', 'PUTT': 1, 'PAR': 5, 'PINDIST': 120.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 463, 'DD': 229.0}
  - Hole Document ID: 2, Data: {'HOLE': 2, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 142.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 463, 'DD': 237.0}
  - Hole Document ID: 3, Data: {'HOLE': 3, 'DDTYPE': nan, 'PUTT': 3, 'PAR': 5, 'PINDIST': nan, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 463, 'DD': nan}
  - Hole Document ID: 4, Data: {'HOLE': 4, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 5, 'PINDIST': 195.0, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 463, 'DD': 259.0}
  - Hole Document ID: 5, Data: {'HOLE': 5, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 79.0, 'SCORE': 7, '1STPU': nan, 'ESC': 7, 'YDS': 463, 'DD': 180.0}
  - Hole Document ID: 6, Data: {'HOLE': 6, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': nan, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 463, 'DD': nan}
  - Hole Document ID: 7, Data: {'HOLE': 7, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 5, 'PINDIST': 98.0, 'SCORE': 6, '1STPU': nan, 'ESC': 6, 'YDS': 463, 'DD': 180.0}
  - Hole Document ID: 8, Data: {'HOLE': 8, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': nan, 'SCORE': 5, '1STPU': nan, 'ESC': 5, 'YDS': 463, 'DD': nan}
  - Hole Document ID: 9, Data: {'HOLE': 9, 'DDTYPE': nan, 'PUTT': 1, 'PAR': 5, 'PINDIST': 121.0, 'SCORE': 4, '1STPU': nan, 'ESC': 4, 'YDS': 463, 'DD': 200.0}
- Course/Tee Document ID: DAVID GUTIERREZ_BLANCA, Data: {'TEE': 'BLANCA', 'CC': 'DAVID GUTIERREZ'}
  Holes Subcollection Data:
  - Hole Document ID: 1, Data: {'HOLE': 1, 'DDTYPE': 'R', 'PUTT': 2, 'PAR': 5, 'PINDIST': 30.0, 'SCORE': 5, '1STPU': 2.0, 'ESC': 5, 'YDS': 483, 'DD': 242.0}
  - Hole Document ID: 10, Data: {'HOLE': 10, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 13.0, 'ESC': 3, 'YDS': 158, 'DD': nan}
  - Hole Document ID: 11, Data: {'HOLE': 11, 'DDTYPE': 'R', 'PUTT': 2, 'PAR': 5, 'PINDIST': 20.0, 'SCORE': 7, '1STPU': 4.0, 'ESC': 7, 'YDS': 557, 'DD': 241.0}
  - Hole Document ID: 12, Data: {'HOLE': 12, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 7.0, 'ESC': 3, 'YDS': 184, 'DD': nan}
  - Hole Document ID: 13, Data: {'HOLE': 13, 'DDTYPE': 'R', 'PUTT': 2, 'PAR': 5, 'PINDIST': 5.0, 'SCORE': 7, '1STPU': 5.0, 'ESC': 7, 'YDS': 505, 'DD': 262.0}
  - Hole Document ID: 14, Data: {'HOLE': 14, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 3, '1STPU': 7.0, 'ESC': 3, 'YDS': 160, 'DD': nan}
  - Hole Document ID: 15, Data: {'HOLE': 15, 'DDTYPE': 'F', 'PUTT': 3, 'PAR': 4, 'PINDIST': 120.0, 'SCORE': 5, '1STPU': 20.0, 'ESC': 5, 'YDS': 385, 'DD': 237.0}
  - Hole Document ID: 16, Data: {'HOLE': 16, 'DDTYPE': 'R', 'PUTT': 1, 'PAR': 4, 'PINDIST': 10.0, 'SCORE': 6, '1STPU': 1.0, 'ESC': 6, 'YDS': 333, 'DD': 210.0}
  - Hole Document ID: 17, Data: {'HOLE': 17, 'DDTYPE': 'R', 'PUTT': 2, 'PAR': 5, 'PINDIST': 25.0, 'SCORE': 6, '1STPU': 4.0, 'ESC': 6, 'YDS': 560, 'DD': 217.0}
  - Hole Document ID: 18, Data: {'HOLE': 18, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 22.0, 'SCORE': 6, '1STPU': 15.0, 'ESC': 6, 'YDS': 426, 'DD': 251.0}
  - Hole Document ID: 2, Data: {'HOLE': 2, 'DDTYPE': 'F', 'PUTT': 2, 'PAR': 4, 'PINDIST': 30.0, 'SCORE': 6, '1STPU': 2.0, 'ESC': 6, 'YDS': 435, 'DD': 208.0}
  - Hole Document ID: 3, Data: {'HOLE': 3, 'DDTYPE': nan, 'PUTT': 2, 'PAR': 3, 'PINDIST': nan, 'SCORE': 5, '1STPU': 2.0, 'ESC': 5, 'YDS': 152, 'DD': nan}
  - Hole Document ID: 4, Data: {'HOLE': 4, 'DDTYPE': 'L', 'PUTT': 2, 'PAR': 4, 'PINDIST': 11.0, 'SCORE': 5, '1STPU': 3.0, 'ESC': 5, 'YDS': 413, 'DD': 284.0}

## Summary:

### Data Analysis Key Findings

*   The data from the Excel file was successfully loaded into a pandas DataFrame containing 2952 rows and 16 columns, including 'UID', 'CC', 'TEE', and hole-specific information.
*   The data was restructured to group it by user (UID), then by course and tee, and finally to organize hole data within each course/tee group.
*   The structured data was uploaded to Firebase Firestore, creating a nested structure where each user has a document under the 'users' collection (using UID as the document ID). Each user document contains a 'CC' subcollection with documents for each course/tee combination, and each course/tee document contains a 'holes' subcollection with documents for each hole (using the hole number as the document ID).
*   Explicitly creating the user documents before attempting to add subcollections was necessary for successful data upload to Firestore.

### Insights or Next Steps

*   The nested structure in Firestore allows for efficient querying of user-specific and course/tee-specific golf data.
*   Consider adding a timestamp to each round's data in the 'CC' subcollection to track performance over time on specific courses and tees.